Angular Добавлено расширение глобального интерфейса Window.
Компилятор выдавал ошибку: error TS2339: Property 'ymaps' does not exist